export interface ICampaignProductView {
    CampaignProductId: string;
    CategoryIndexer: {};
    CurrencyCode: string;
    CurrencyLocale: string;
    CurrencyName: string;
    CurrencySymbol: string;
    DisplayLocalFormat: null;
    DisplayOrder: number;
    DisplayRank: number;
    DisplayText: string | null;
    EventDate: null;
    EventDateFormal: string;
    ExtendedPrice: number;
    IsEventActive: boolean;
    IsSubscriable: boolean;
    IsTaxable: boolean;
    MaxQuantity: number;
    MetaDescription: string | null;
    MetaKeywords: string | null;
    MinQuantity: number;
    NumberOfPayments: number;
    PostalCodes: [];
    Price: number;
    ProductAttributes: [];
    ProductCode: string;
    ProductName: string;
    ProductSku: string;
    ProductType: string;
    ProductTypeId: number;
    PropertyIndexer: {};
    RelatedProductIds: [];
    RelatedProducts: [];
    ReportPrice: number;
    Shipping: number;
    ShortName: string | null;
    SubscriptionType: null;
    SubscriptionTypeId: null;
    TaxExtendedPrice: boolean;
    TimeZoneDisplayId: null;
    TimeZoneId: null;
    Title: null;
    VideoHeight: null;
    VideoLink: null;
    VideoLinkMobile: null;
    VideoWidth: null;
}
